export function Tabela() {
    return(
        <table>
            <thead>
            <tr>
                <th>
                    Nome
                </th>
                <th>
                    IBU
                </th>
                <th>
                    Marca
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Heineken
                </td>
                <td>
                    33
                </td>
                <td>
                    Ambev
                </td>
            </tr>
            </tbody>
        </table>
    )
}